language: scala
scala:
- 2.12.3

script:
  - sbt test
  - npm run build

deploy:
  provider: heroku
  api_key:
    secure: Eh4guBR7gVxZktngcQIlIiGvfme1SR0Iq0qbxBbnqb7SNrhlCxvzhu5YRXBnKt6z1iUdt87U7SjTU7yamolIIIt4o8pDl1AwLmDTMYd8T0yJ0E63GnfNygIZez4BUMfPHbt8N8or+N0mOWxOygnL36Ac4K5PZH84Fg6USAOKcBi8deySuhpnI0iEbzjVWRFN/6ck8TkCeuVwM7JxiIK/16Sf9KBIf3/ufQVrs99dux+Z0lyq0eniHlLTx9AH9GTCB3DDS+elCESFaM622HAdPB56dZ+Ml/r1taEHRzC9v8580QPIRUtVbLjgSwxo53cf5s9J+c9c/i5NCubi+1xerOvX9Ni05TqE/+OZaofnzzaRD4VpWAO3BhiW3TpIT/hgJwM8LOtWV0/5r1PddLsvfSHmjfBCGpRj/2pFRNksD1MFCiNX1K87+BqNO/4VEHRm8FMkx2hW5F5FUyRc7Xdmp+jkwPtHVfaLDvH56A7JQM9WmL4s7r3sLHX+g8UA49WQmLzf+Ott38lU7TD0IzgY5r2n+JswSHXh/AImqQCZD0iEJjGYUsUq3zgT+1YT+tT2svADYVOhkP8/23TJAbgP8MHsRjAtHXfzqVtkgFYnwT7pmKltODv5tK396GoOFjd2+uhrXYs9IgFo/TO6H5pZpvPi2PVWwSjysRmu7q9u8Q4=
